### ISSUE TITLE
stop or destroy the fireworks canvas

### ISSUE THREAD

**Issue by atlal22** [mgrigajtis/jquery-fireworks#1]
Hello mgrigajtis
Can I ask you
how can i stop or destroy the fireworks canvas in the jquery-fireworks.js

thank you

**Comment by mgrigajtis** [comment]
You should be able to achieve this in the JavaScript:
`delete canvasObject;`

Let me know if this solves the problem for you.

**Comment by ruhul440** [comment]
> You should be able to achieve this in the JavaScript: `delete canvasObject;`
> 
> Let me know if this solves the problem for you.

Hi, Thank you for your solution. Can you tell me, how can I apply this code on the plugin?
